name: auto-check

on:
  push:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm check
