name: auto-check

on:
  push:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  code-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm check

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm install
      - run: pnpm zip
